#include <criterion/criterion.h>
#include "../src/astro_maths.h"


#define FLOAT_PT_TOLERANCE 0.00001

/*
  All expected results of coordinates conversions has been taken from various
  online tools, like Google
  TODO: compare results from those generated by an astronomy library, like astropy
*/


Test(astro_maths_tests, test_deg_to_rad) {
  float deg0 = 0.0;
  cr_expect(deg_to_rad(deg0) == 0.0, "0° should give 0 rad");
  
  float deg1 = 1.0;
  float expected1 = 0.0174533;
  cr_expect(deg_to_rad(deg1) - expected1 < FLOAT_PT_TOLERANCE,
	    "1° should be equal to 0.0174533 rad");

  float deg180 = 180.0;
  float expected2 = 3.14159;
  cr_expect(deg_to_rad(deg180) - expected2 < FLOAT_PT_TOLERANCE);
  
  float deg360 = 360.0;
  float expected3 = 6.28319;
  cr_expect(deg_to_rad(deg360) - expected3 < FLOAT_PT_TOLERANCE,
	    "360° should be equal to 6.28319 rad");
}


Test(astro_maths_tests, test_hms_to_deg) {
  HmsCoords hms0 = {.h = 0, .m = 0, .s = 0};
  cr_expect(hms_to_degrees(&hms0) == 0.0);
  
  HmsCoords hms1 = {.h = 12, .m = 27, .s = 43};
  float expected1 = 186.9292;
  cr_expect(hms_to_degrees(&hms1) - expected1 < FLOAT_PT_TOLERANCE);

  HmsCoords hms2 = {.h = 1, .m = 1, .s = 0};
  float expected2 = 15.25;
  cr_expect(hms_to_degrees(&hms2) - expected2 < FLOAT_PT_TOLERANCE);
}



